FROM golang:1.10.2 as builder
WORKDIR /go/src/app
COPY . .
WORKDIR /go/src/app/discovery
RUN go get -d -v
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o discovery .

FROM busybox
WORKDIR /root/
COPY --from=builder /go/src/app/discovery/discovery /discovery
CMD ["/discovery"]